# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.

# CloudFoundry Credentials
CF_ENDPOINT:
CF_TOKEN:
CF_REFRESH_TOKEN:

# Allow register users by email (true/false)
EMAIL_REGISTER_ENABLED: true

# AT&T Client Tokens (https://auth.tfoundry.com/apps)
#ATT_CLIENT_ID: ''
#ATT_CLIENT_SECRET: ''

# Facebook Client Tokens (https://developers.facebook.com/apps)
#FACEBOOK_KEY: ''
#FACEBOOK_SECRET: ''

# Github Client Tokens (https://github.com/settings/applications)
#GITHUB_KEY: ''
#GITHUB_SECRET: ''

# Linkedin Client Tokens (https://www.linkedin.com/secure/developer)
#LINKEDIN_KEY: ''
#LINKEDIN_SECRET: ''

# Twitter Client Tokens (https://dev.twitter.com/apps)
#TWITTER_KEY: ''
#TWITTER_SECRET: ''
