# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.

# CloudFoundry Credentials
CF_ENDPOINT:
CF_ADMIN_USER:
CF_ADMIN_PASSWORD:

# Cloud Foundry Organization where to assign new users. If not set or does not exist,
# it will create a new Organization with a random name for each user.
#CF_ORGANIZATION: ''

# Roles to assign to users when assigning to an Organization.
#CF_ORGANIZATION_ADD_MANAGER: false
#CF_ORGANIZATION_ADD_BILLING_MANAGER: false
#CF_ORGANIZATION_ADD_AUDITOR: false

# Cloud Foundry Space where to assign new users. If not set, it will create (or reuse) a Space called 'development'.
#CF_SPACE: 'development'

# Roles to assign to users when assigning to a Space.
#CF_SPACE_ADD_MANAGER: false
#CF_SPACE_ADD_DEVELOPER: false
#CF_SPACE_ADD_AUDITOR: false

# Allow register users by email (by default true).
#EMAIL_REGISTER_ENABLED: false

# Recaptcha keys (http://www.google.com/recaptcha/whyrecaptcha)
#RECAPTCHA_PUBLIC_KEY: ''
#RECAPTCHA_PRIVATE_KEY: ''

# Overrides the Omniauth host (eg if you want to enforce a http/https callback uri)
#OMNIAUTH_FULL_HOST: ''

# AT&T Client Tokens (https://apimatrix.tfoundry.com/apps)
#ATT_CLIENT_ID: ''
#ATT_CLIENT_SECRET: ''

# Facebook Client Tokens (https://developers.facebook.com/apps)
#FACEBOOK_KEY: ''
#FACEBOOK_SECRET: ''

# Github Client Tokens (https://github.com/settings/applications)
#GITHUB_KEY: ''
#GITHUB_SECRET: ''

# Restrict Github users belonging to an organization
#GITHUB_ORGANIZATION: ''

# Linkedin Client Tokens (https://www.linkedin.com/secure/developer)
#LINKEDIN_KEY: ''
#LINKEDIN_SECRET: ''

# Twitter Client Tokens (https://dev.twitter.com/apps)
#TWITTER_KEY: ''
#TWITTER_SECRET: ''
